### DISCUSSION TITLE
how to use jwt in helidon-se 4

### DISCUSSION THREAD

**Discussion by sixwaaaay** [helidon-io/helidon#7930] [Q&A] [answered]
the project generated by helidon starter doesn't work.
there are only 'signing-jwk.json', 'verifying-jwk.json' and a code snippet in 'application.yaml'.
there is no jwt example in readme.md of generated project.
```yaml
server:
  port: 8080
  host: 0.0.0.0
  features:
    
    security:
      defaults:
        authenticate: true
      web-server:
        # protected paths on the web server - do not include paths served by Jersey, as those are protected directly
        paths:

security:
  config.require-encryption: false
  properties:
  providers:
    - jwt:
        atn-token:
          jwk.resource.resource-path: "verifying-jwk.json"
          jwt-audience: "http://my.service"
        sign-token:
          jwk.resource.resource-path: "signing-jwk.json"
          jwt-issuer: "http://my.server/identity"
          outbound:
            - name: "propagate-token"
              hosts: ["*.internal.org"]
            - name: "generate-token"
              hosts: ["1.partner-service"]
              jwk-kid: "partner-1"
              jwt-kid: "helidon"
              jwt-audience: "http://1.partner-service"
```
