### ISSUE TITLE
4.x: SE openapi-generator for arrays in query-params doesn't respect `explode`

### ISSUE THREAD

**Issue by creedasaurus** [helidon-io/helidon#10068]
## Environment Details
* Helidon Version: 4.2.1
* Helidon SE
* JDK version: 21
* OS: macos/any

----------

## Problem Description

I am using the openapi-generator for Helidon SE and I'd like to solve some issues I've seen around arrays in query params, including things like whether or not `explode` is supported and also defaults around optional arrays.

Ultimately I'd want to answer 2 separate questions related to array query params:

1. should the expected Helidon-parsed result of an "optional" array in the query be
    an `Optional<List<String>>` or a `List<String>` and if it isn't specified in the request
    should the passed result be `Optional.empty()` or `Collections.emptyList()` or an equivalent?

2. it seems the default, and only parsing of arrays is done via `explode`'d params, but could we have this
    be either-or, depending on a configuration, or depending on the openapi-generator for Helidon?

```yaml
/fake/optional-and-required-array:
  get:
    # ...
    parameters:
      - name: optionalArrayParam
        in: query
        required: false
        explode: false # <----- explode is "true" for "form" style query, which is the default
        schema:
          type: array
          items:
            type: string
```

I guess this is handled different by different applications and there isn't necessarily a
standard around "arrays in query params", but the [open-api docs](https://spec.openapis.org/oas/v3.0.3.html#parameter-locations) suggest
that you can specify the `explode` parameter to indicate how you'd want
these to be used. e.g.:

```yaml
# style: form
# explode: false
request: /path?color=blue,black,brown
```

or:

```yaml
# style: form
# explode: true
request: /path?color=blue&color=black&color=brown
```

## Steps to reproduce

My repo: https://github.com/creedasaurus/helidon-bug-repros

```
git clone git@github.com:creedasaurus/helidon-bug-repros.git
```

and

```
mvn verify
```

Take a look at the `./spec/openapi.yaml` document and the params there, and then you can check the tests and see what I mean about the handler.
