### ISSUE TITLE
Service registry support for Jakarta Persistence

### ISSUE THREAD

**Issue by Tomas-Kraus** [helidon-io/helidon#10141]
Persistence unit context (EntityManaferFactory) and persistence session (EntityManager) should be available in service registry.
It should be created from Config node with following structure:

```
persistence-units:
  jakarta:
    - name: "PU-name"
      data-source: "test"
      provider-class-name: "org.eclipse.persistence.jpa.PersistenceProvider"
      init-script: "init-database.sql"
      drop-script: "drop-database.sql"
      properties:
        jakarta.persistence.schema-generation.database.action: drop-and-create
```

**Comment by tomas-langer** [comment]
This is the configuration used in the PR:

```yaml
data-sources:
  sql:
    - name: "test"
      provider.hikari:
        username: "user"
        password: "changeit"
        url: "jdbc:mysql://localhost:3306/testdb"

persistence-units:
  jakarta:
    - data-source: "test"
      # EclipseLink properties
      properties:
        eclipselink.target-database: "MySQL"
        eclipselink.target-server: "None"
        eclipselink.weaving: false
        eclipselink.logging.level: "FINEST"
        eclipselink.logging.level.weaver: "OFF"
        eclipselink.logging.parameters: true
        jakarta.persistence.schema-generation.database.action: drop-and-create
```
