### ISSUE TITLE
Allow users to selectively enable/disable individual metrics via config and builder

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#3537]
## Environment Details
* Helidon Version: 2.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Currently, Helidon allows users to selectively enable and disable single metrics of the `base` type using config and (after #2180 and its PR #3441) all of metrics and by component (when the component is written to support it).

This enhancement would allow users to control an entire metric type (base, vendor, and application) with a single setting and also selectively control metrics within each type.

Users could use configuration like this:

```
metrics:
    registries:
        - type: application | base | vendor
          enabled: true/false
          filter: 
              exclude: '<pattern>'
              include: '<pattern>'
```
By default, Helidon metrics enables all three registry types and applies no filter.

The `<pattern>` expression for `excluded` or `included` is a regex. 

For a candidate string to pass the filter, it must _not_ match the `excluded` pattern. Further, if the filter contains an `included` pattern, the candidate string must match it. 

For example, using
```
metrics:
  registries:
    - type: application
      filter:
        exclude: expensive.*|costly.*
```
would accept all application metrics except those beginning with `expensive` or `costly`.

Adding an `included` pattern changes the behavior:
```
metrics:
  registries:
    - type: application
      filter:
        exclude: expensive.*|costly.*
        include: mine.*|yours.*|costly\.group.*
```
Note that:
1. Application metrics starting with `expensive` or `costly` are rejected. The `costly\.group.*` part of the `included` pattern is essentially ignored. The filtering is strictly regex string matching; it does not recognize any implied dotted-name hierarchy or treat a more specific pattern as overriding a more general one.
2. Any metric starting with `mine` or `yours` passes.
3. Any other metrics name is rejected.

When an application or a Helidon component registers a metric in a registry, Helidon checks the metric name against the settings for that registry. If all the following conditions are true, then Helidon registers a full-functional metric:
- full-featured metrics behavior is active (the full metrics implementation is on the runtime path and metrics is enabled)
- the relevant registry type is enabled
- there is no filter, or the metrics name passes the filter as described above.

Otherwise, Helidon registers a no-op metric and suppresses output about that metric from the metrics endpoints.

As a debugging aid, `FINE`-level logging could report each metric name that Helidon checks and the outcome of filtering it.

Note that the existing syntax used for controlling `base` metrics remains valid although for clarity users should use one or the other, not both. Using both should be considered as unsupported and could produce unpredictable results.

The enhancement will also be supported via builder with `MetricsSettings` (added in #3441 to resolve #2180).
