### ISSUE TITLE
Document thread pool tuning in JDBCDbClientProvider

### ISSUE THREAD

**Issue by klustria** [helidon-io/helidon#3735]
## Environment Details
* Helidon Version: all
* Helidon SE

----------

## Problem Description
There is currently no documentation that describes how to tune the thread pool for JDBCDbClientProvider. Currently, the pool defaults to the following values: 10 default core pool size, 50 max pool siz, and 0 pool growth rate of 0. Because of this, the ceiling for the # of threads will stop at 10. There may be situations where jdbc client provider will be exposed to highly intensive usage  where 10 threads would not be enough and will eventually cause thread starvation. The following are examples of how the ThreadExecutor can be configured to grow more and allow for more threads to service more JDBC connection :
1. Using growth-rate (although this is still experimental)
   ```
   db:
     executor-service:
       growth-rate: 10
   ```
1. Using core-pool-size and max-pool-size
   ```
   db:
     executor-service:
        core-pool-size: 100
        max-pool-size: 100
   ```
1. Or combination of both
   ```
   db:
     executor-service:
        core-pool-size: 100
        max-pool-size: 100
        growth-rate: 10
   ```
