### ISSUE TITLE
OCI Object Storage Health Check still depends on deprecated configuration / code in helidon-integrations-oci-objectstorage

### ISSUE THREAD

**Issue by vamshikrishna83** [helidon-io/helidon#4381]
OciObjectStorageHealthCheck still depends on deprecated classes / code which indirectly depends on old configuration entries in application.yaml file. It would be nice to get rid of dependencies on old code / configuration properly.

For instance, even after updating my application to make use of new OCI CDI Extension, i am forced to have the below configuration in application.yaml so that the health check code works. This is due to the fact that HealthCheck class is dependent on old integration library, which in-turn to work requires to the below configuration to be able to establish connectivity to ObjectStorage properly.

```yaml
 oci:
   default:
     config:
       instance-principal:
         enabled: true
     objectstorage:
       namespace: "tenancy"
``` 

## Environment Details
* Helidon Version: 2.5.1
* Helidon MP
* JDK version: JDK 17
* OS: Windows 10
* Docker version (if applicable): NA
