### ISSUE TITLE
3.x: quickstart archetype has bad k8s app.yaml and missing README instructions

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#4756]
## Environment Details
* Helidon Version: 3.0.1
* Helidon SE 

----------

## Problem Description

The 3.0.1 quickstart archetype has a bad k8s `app.yaml` and missing `README` instructions

Generate the Helidon SE Quickstart (probably MP too) using the archetype (or CLI):

```
mvn -U archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-se \
    -DarchetypeVersion=3.0.1 \
    -DgroupId=io.helidon.examples \
    -DartifactId=helidon-quickstart-se \
    -Dpackage=io.helidon.examples.quickstart.se
```

Inspect `app.yaml`. You'll see it only has the `Service` section and not `Deployment`. If you apply this app.yaml you'll only get a service with no pods.

Also, there is no Kubernetes information in the README.  To see how this should work do the above but replace "3.0.1" with "2.5.2"

**Comment by barchetta** [comment]
Workaround: Use `app.yaml` from 2.x:
```
kind: Service
apiVersion: v1
metadata:
  name: helidon-quickstart-se
  labels:
    app: helidon-quickstart-se
spec:
  type: NodePort
  selector:
    app: helidon-quickstart-se
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-quickstart-se
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helidon-quickstart-se
  template:
    metadata:
      labels:
        app: helidon-quickstart-se
        version: v1
    spec:
      containers:
      - name: helidon-quickstart-se
        image: helidon-quickstart-se
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
```
