### ISSUE TITLE
No config documentation for Security.Builder.addProvider(SecurityProvider provider, String name)

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#5430]
No where do we document the `name` config key used to name a provider. For example:

```yaml
  providers:
    - jwt:
        optional: true
        atn-token:
          jwk.resource.resource-path: "verifying-jwk.json"
          jwt-audience: "http://example.helidon.io"
    - name: "jwt2"
      jwt:
        optional: true
        atn-token:
          jwk.resource.resource-path: "verifying-jwk.json"
          jwt-audience: "http://example.helidon.io"
```
