### ISSUE TITLE
Only one openapi.ui.options setting takes effect

### ISSUE THREAD

**Issue by extact-io** [helidon-io/helidon#5998]
## Environment Details
* Helidon Version: 3.1.0
* Helidon MP
* JDK version: OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
* OS: Windows10
----------

## Problem Description
Even if multiple settings are made to `openapi.ui.options`, only one Option setting is reflected in OpenAPI UI.

## Steps to reproduce
Set Config as follows
```yaml
openapi.ui:
  options:
    title: Test Title
    themeHref: theme-muted.css
    displayOperationId: true
    footer: test footer
```

Only the `displayOperationId` is reflected and the operationId is output, but the `title` and `themeHref` are the default settings of Helidon as shown in the following HTML and the settings are not reflected.
```html
<head>
    <meta charset="UTF-8">
    <title>Helidon OpenAPI UI</title>
    <link rel="stylesheet" type="text/css" href="swagger-ui.css">
    <link rel="stylesheet" type="text/css" href="theme-feeling-blue.css">
    ...
</head>
```

If I set only one setting as follows
```yaml
openapi.ui:
  options:
    title: Test Title
````
The `title` is reflected as follows
```html
<head>
    <meta charset="UTF-8">
    <title>Test Title</title>
    <link rel="stylesheet" type="text/css" href="swagger-ui.css">
    <link rel="stylesheet" type="text/css" href="theme-feeling-blue.css">
    ...
</head>
````

## perhaps,,
at io.helidon.integrations.openapi.ui.OpenApiUiFull.Builder#convertOptions
```java
nextKey:
for (Map.Entry<String, String> entry : options.entrySet()) {
    for (Option opt : Option.values()) {
        if (opt.name().equals(entry.getKey())) {
            result.put(opt, entry.getValue());
            break nextKey;
        }
    }
    unrecognizedKeys.add(entry.getKey());
}
```
Since there is a labeled break (nextKey), is it because the search for the key has ended at the first match?
