### ISSUE TITLE
ConfigBean Map<> support

### ISSUE THREAD

**Issue by trentjeff** [helidon-io/helidon#6382]
ConfigBeans currently do not support Map<> types.

The workaround is to use a List (or Set), and then write a default function that will take that List (or Set) and turn it into a map.  See FakeServerConfig for usage of `sockets()`.

**Comment by trentjeff** [comment]
idea: anything that is a map by convention needs to have a `name()` attribute, and that will serve as the key.

To find places in the code that related to this, just search for this issue #.

**Comment by tomas-langer** [comment]
Map conversion already exists in config, and config beans should work similar to that

- missing type -> no map
- value type -> no map
- object type -> map of child keys to their content
- list type -> map of list indexes to their content

Example 1 (list type):
```
sockets:
 - port: 8080
    host: "localhost"
 - port: 8081
    host: "localhost"
```
would map to:
Map<String, Socket>
0: Socket (localhost:8080)
1: Socket (localhost:8081)

Example 2 (object type):
```
sockets:
  admin:
    port: 8080
    host: "localhost"
  business:
    port: 8081
    host: "localhost"
```
would map to:
Map<String, Socket>
admin: Socket (localhost:8080)
business: Socket (localhost:8081)
