### ISSUE TITLE
Kafka connector- broker does not support INIT_PRODUCER_ID

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#6718]
Helidon Versions: 2.6.1 and newer, 3.2.1 and newer, 4.0.0-ALPHA7 and newer

There is a known issue with OSS(OCI Streaming Service) and older versions of Kafka [KIP-679](https://cwiki.apache.org/confluence/display/KAFKA/KIP-679%3A+Producer+will+enable+the+strongest+delivery+guarantee+by+default) which enabled backward incompatible feature by default, workaround is explicitly disabling producer idempotence with `enable.idempotence: false`

Exception:
```
org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support INIT_PRODUCER_ID
```
Workaround:
```
enable.idempotence: false
```

Messaging connector config example:
```yaml
mp.messaging:
 connector:
   helidon-kafka:
     enable.idempotence: false
     bootstrap.servers: ${oci.test-stream.endpoint}:${oci.test-stream.port}
     ...
```
