### ISSUE TITLE
TracingFeature as an Observer

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#7629]
As of 4.0.0-M2, tracing is not part of the "ObserveFeature" providers, it is a separate ad-hoc feature.

Tracing logically belongs in the category of observability, it is odd to set up routing with both ObserveFeature and TracingFeature:

```java
routing.addFeature(TracingFeature.create(tracer))
            .addFeature(ObserveFeature.create())
```

We should implement TracingFeature as an "Observer":
- consistent with other observability related features (health, metrics)
- discoverable off class-path

**Comment by tomas-langer** [comment]
Other observability features expose endpoint and are better aligned with the "observe" feature being registered on a single routing.
Tracing adds a filter on the routing, and as such is usually registered on the "business" socket (in case observability endpoints are registered on a custom socket).
This introduces a problem, as we want to have an "observability" feature, yet we need to use routing builder for a different socket. 
This is solved in metrics by having additional methods on the observer, but we do not have a single good way of doing this (and it is relevant for other thing as well, such as access log).

I would like to design tracing observer and related infrastructure to support multiple sockets nicely and easy to configure.

Requirements I think are relevant:
- configuration per socket (tags for each socket, different level of detail etc.)
- possible automation of socket discovery (so a feature can know about additional sockets, ideally receiving a socket name + routing builder for that socket)

I think this would require some bigger changes in the way that our server is set up if we wanted to automate this. It is easier in CDI (and in the future with injection), as there we have full control of the socket setup, and so we can easily call appropriate methods on the tracing observer.

As this can be done in a backward compatible manner (deprecating `helidon-webserver-tracing` and introducing `helidon-webserver-observe-tracing` we do not need to push this feature as a very high priority.

**Comment by romain-grecourt** [comment]
Not sure I understand exactly how this can be done in a compatible manner. 

Some possibilities:
- observe provider has to be socket aware and we change the way it must be registered (E.g. we move it at the server level), `ServerFeature` ?
- we make `HttpFeature` registered on all sockets and we pass the socket information to the `setup` method

We could make the 2nd scenario backward compatible, e.g. by overloading the `setup` method and having a no-op default implementation of the method.

Also, I can't see how we can have builders passed around in runtime objects.

**Comment by romain-grecourt** [comment]
I actually see a way that is backward compatible, here is a take:

```java
interface ServerFeature<T> extends Supplier<ServerFeature>, ServerLifecycle {
    void setup(ListenerConfig listenerConfig, T routing);
}

interface ServerHttpFeature extends ServerFeature(HttpRouting.Builder) {
}

class ObserveFeature extends HttpFeature, ServerHttpFeature {

   @Override
   void setup(ListenerConfig config, HttpRouting.Builder routing) {
   }

   @Override
   void setup(HttpRouting.Builder routing) {
   }
}
```

```java
WebServer server = WebServer.builder()
        .addFeature(SecurityFeature.create())
        .addFeature(CorsFeature.create())
        .addFeature(ObserveFeature.create())
        .routing(Main::routing)
        .build()
        .start();
```

In the code above, the server feature is created using global config:

```yaml
server:
  port: 8080
  host: "localhost"
  sockets:
    - name: "admin"
      port: 8081
      bind-address: "localhost"
observe:
  # use admin as the socket for the observe feature
  # if registered via HttpRouting.Builder.addFeature, this is ignored
  socket: 'admin'
  observers:
    - tracing: 
      # override the socket to use for the tracing observer
      socket: '@default'
security:
  web-server:
    # use '@default' as the socket for the 'paths'
    # if registered via HttpRouting.Builder.addFeature, this is ignored
    socket: '@default'
    paths:
      - path: "/user[/{*}]"
        methods: ["get"]
        authenticate: true
      - path: "/observe/[/{*}]"
        methods: ["get"]
        authenticate: true
        # override the socket to use for this entry
        socket: '@admin'
cors:
  # use '@default' as the socket for the 'paths'
  # if registered via HttpRouting.Builder.addFeature, this is ignored
  socket: '@default'
  paths:
    - path-pattern: /greeting
      allow-origins: ["http://foo.com"]
      allow-methods: ["PUT", "DELETE"]
    - path-pattern: "/observe/[/{*}]"
      allow-origins: ["http://other.com"]
      allow-methods: ["PUT", "DELETE"]
      socket: '@admin'
```
 
If we update all implementations of `HttpFeature` to also implement `ServerHttpFeature` that means we could potentially implement #7630
