### ISSUE TITLE
Decoupled CORS supports

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#7631]
Currently (as of 4.0.0-M2), the CORS support is an adhoc solution implemented in various component that need it (E.g. OpenApi).
The configuration is nested under each component.

How about having a centralized solution implemented as a filter, similar to SecurityFeature.

E.g. 
```yaml
cors:
    paths:
        - path: "/greeting[/{*}]"
          methods: ["GET"]
          allow-origins: ["http://foo.com", "http://there.com", "http://other.com"]
          allow-methods: ["PUT", "DELETE"]
```

```java
static void routing(HttpRouting.Builder routing) {
    routing.addFeature(CorsFeature.create())
           .register("/greet", GreetService::new)
}
```
