### ISSUE TITLE
Default redirect-attempt-param 

### ISSUE THREAD

**Issue by Karthik2177** [helidon-io/helidon#7753]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 3.2.2
* Helidon MP
* JDK version: 17.0.3
* OS: Mac OS
* Docker version (if applicable): N/A

----------

## Problem Description

We are using OIDC provider for SSO integration.
After successful authentication, the redirect URL is appended with param `?h_ra=1`
`https://xxx-test.com/api/ui-infrastructure/suis-index-ms/v1/applications/ui:2039e6cf-d57a-4ae4-8991-3ac7fc1a2566/redwood/rwdref?h_ra=1 `
We don't see the configuration options to not appending the param "h_ra", I think we can do one workaround by implementing Filter to remove this param.

@srusen, was expecting that configuration to be possible by setting the oidc.redirect-attempt-param as empty. We tried this option, still the default param is getting appended.

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

OidcSupport.increaseRedirectCounter(String state) method appending the 'h_ra' param.
Example to configure SSO : https://github.com/helidon-io/helidon/blob/3.2.2/examples/security/idcs-login/src/main/resources/application.yaml
My application Configuration:
```yaml
 security:
  enabled: "${indexService.authenticate}"
  config.require-encryption: false
  properties:
    idcs-uri: "${idcs.identityServiceInstanceURL}"
    idcs-client-id: "${idcs.oauthClient.clientId}"
    idcs-client-secret: "${idcs.oauthClient.clientSecret}"
  provider-policy:
    type: "COMPOSITE"
    authentication:
      - name: "spectra-auth"
        flag: "MAY_FAIL"
      - name: "oidc-delegator"
        flag: "MAY_FAIL"
  providers:
    - spectra-auth:
        authentication:
          authenticate: ${indexService.authenticate}
    - abac:
        # OIDC needs an Authorization Provider that is why abac needs to be configured
        fail-if-none-validated: true
    - oidc:
        client-id: "${idcs.oauthClient.clientId}"
        client-secret: "${idcs.oauthClient.clientSecret}"
        identity-uri: "${idcs.identityServiceInstanceURL}"
        # support for non-public signature JWK (and maybe other IDCS specific handling)
        server-type: "idcs"
        logout-enabled: true
        redirect: true
        redirect-uri: "${indexService.path}/oidc/redirect"
        # this provider is only used for SSO
        header-use: false
        post-logout-uri: "${indexService.path}/oidc/logout"
        frontend-uri: "${environment.host}"
    - oidc-delegator:
        paths: ["/applications"]
```
