### ISSUE TITLE
4.x: Unable to set Proxy in Config file for WebClient

### ISSUE THREAD

**Issue by klustria** [helidon-io/helidon#7801]
## Environment Details
* Helidon Version: 4.x

----------

## Problem Description
Adding proxy in config file (application.yaml) for webclient fails. 

## Steps to reproduce
1. `application.yaml` setting:
    ```
    client:
       proxy:
         host: "hostName"
         port: 80
         no-proxy: ["localhost:8080", ".helidon.io", "192.168.1.1"]
    ```
2. And client code:
    ```
            WebClient client = WebClient.builder()
                    .baseUri(url)
                    .config(config.get("client"))
                    .build();
    ```

fails with this error:
```
Exception in thread "main" io.helidon.config.ConfigMappingException: Mapping of value stored under key 'client.proxy' to type 'class io.helidon.webclient.api.Proxy' has failed: No mapper configured
```

## Observation
In comparison to TLS which works, in the generated HttpConfigBase->BuilderBase->config , it has this statement to get Tls config:
```
config.get("tls").map(TlsConfig::create).ifPresent(this::tls);
```
while proxy which fails retrieves config by doing this:
```
config.get("proxy").as(Proxy.class).ifPresent(this::proxy);
```
It looks like Proxy will need to have ProxyConfig generated via a ProxyConfigBluePrint and also use 
```
config.get("proxy").map(ProxyConfig::create)
```
instead of 
```
config.get("proxy").as(Proxy.class)
```
