### ISSUE TITLE
4.x: protocol-configs does not allow h2 (http/2)

### ISSUE THREAD

**Issue by klustria** [helidon-io/helidon#7802]
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Even though http/2 is added as a dependency in the application, adding `h2` in protocol-configs fails. `h2` is used because it is the config-key for http/2. On the other hand, using http_1_1 to set http/1.1 config works fine.

## Steps to reproduce
1. `application.yaml` setting:
    ```
    client:
        protocol-configs:
            http_1_1:
                max-header-size: 20000
                validate-request-headers: true
            h2:
                prior-knowledge: true
    ```
2. Add this in pom.xml of the project's application:
    ```
        <dependency>
            <groupId>io.helidon.webclient</groupId>
            <artifactId>helidon-webclient-http2</artifactId>
        </dependency>
    ```
3. And client code:
    ```
            WebClient client = WebClient.builder()
                    .baseUri(url)
                    .config(config.get("client"))
                    .build();
    ```
fails with:
```
Exception in thread "main" io.helidon.common.config.ConfigException: Unknown provider configured. Expected providers with types: [h2], but only the following providers are supported: [http_1_1], provider interface: io.helidon.webclient.spi.ProtocolConfigProvider, configured service: io.helidon.webclient.spi.ProtocolConfig
```
