### ISSUE TITLE
4.x: archetype test configuration uses a file named application.yaml

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#7843]
## Environment Details
* Helidon Version: 4.0.0-RC1

## Problem Description

Having a file called `application.yaml` under `src/test/resources` works with the default config sources (I.e. `Config.create()`).
However it means duplicating content from `src/main/resources/application.yaml`.

A better practice would be to have a file called `application-test.yaml` and to setup the config source using meta-config:
```yaml
# taken from examples/quickstarts/helidon-quickstart-se
sources:
  - type: "inlined"
    properties:
      server.port: 0
  - type: "classpath"
    properties:
      resource: "application.yaml"
  - type: "classpath"
    properties:
      resource: "application-test.yaml"
```

This allows users to override config defined in `src/main/resources/application.yaml`.
