### ISSUE TITLE
4.x - Metrics does not obey config settings

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#7911]
## Environment Details
* Helidon Version: 4.0.0
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
`MetricsFeature`, initialized using `MetricsObserverConfig`, does not properly obey all metrics config settings.

## How config is _not_ handled completely correctly under `server.features.observe.observers.metrics`
In the 4.0 SE QuickStart app, edit `application.yaml` so it contains this:
```yaml
app:
  greeting: "Hello"

server:
  port: 8080
  host: 0.0.0.0
  features:
    observe:
      observers:
        metrics:
          scoping:
            scopes:
              - name: vendor
                filter:
                  include: requests.l.*
          key-performance-indicators:
            extended: true
```
The `key-performance-indicators` section should enable the extended KPI meters (their names begin with `requests` and are in the `vendor` scope) and the `scoping` section should allow only meters in the `vendor` scope with names beginning with `requests.l` (lower-case "ell"). (Strictly speaking the regex allows any meter starting with `requests` followed by any single character followed by "l" but using an unquoted dot does not affect the problem.)

Now rebuild and run the app and then run the following commands:
```bash
curl http://localhost:8080/greet ; curl -v -H "Accept: application/json" 'http://localhost:8080/observe/metrics' | jq
```

Observe the following (partial) `yaml` response:
```yaml
{
  "vendor": {
    "requests.count": 2,
    "requests.load": 2,
    "requests.longRunning": 0,
    "requests.deferred": 0,
    "requests.inFlight": 1
  },
```
The extended KPI meters were correctly enabled (`count` is the only non-extended KPI meter; the others are in the extended category) _but_ the filtering _did not_ exclude those names that do not start with `requests.l`.
