### ISSUE TITLE
[3.x] - Wrong Tracing/Zipkin config created when using Project Starter

### ISSUE THREAD

**Issue by dalexandrov** [helidon-io/helidon#8071]
## Environment Details
* Helidon Version: 3.2.3
* Helidon SE
* JDK version: 17/21
* OS: OSX

----------

When creating Helidon SE version 3.2.3 project using starter, with Zipkin Tracing
https://helidon.io/starter/3.2.3?step=9&app-type=custom&tracing=true&tracing.provider=zipkin

wrong tracing configuration is created:

```
tracing:
  zipkin:
    service: "helidon-service"
    protocol: "https"
    host: "192.168.1.1"
    port: 9987
    api-version: 1
    # this is the default path for API version 2
    path: "/api/v2/spans"
    tags:
      tag1: "tag1-value"
      tag2: "tag2-value"
    boolean-tags:
      tag3: true
      tag4: false
    int-tags:
      tag5: 145
      tag6: 741
```
the application fails to start.

The proposed config is:

```
tracing:
  service: "helidon-service"
  protocol: "https"
  host: "192.168.1.1"
  port: 9987
  api-version: 1
  # this is the default path for API version 2
  path: "/api/v2/spans"
  tags:
    tag1: "tag1-value"
    tag2: "tag2-value"
  boolean-tags:
    tag3: true
    tag4: false
  int-tags:
    tag5: 145
    tag6: 741
```
