### ISSUE TITLE
[4.x] - Tracing issues 

### ISSUE THREAD

**Issue by dalexandrov** [helidon-io/helidon#8103]
## Environment Details
* Helidon Version: 4.0.1
* Helidon SE 
* JDK version: 21
* OS: OSX

The following Helidon SE app created:
https://helidon.io/starter/4.0.1?step=9&app-type=custom&tracing=true
--------

* `tracing.enabled` not working. With tracing.enabled=false, still `SEVERE: Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:14250`
* attempting to rename the "HTTP Request" span doesn't seem to have an effect
* disabling content-write span doesn't seem to have an effect

**Comment by tjquinno** [comment]
@dalexandrov Are the failing attempts to rename the span and disable the `content-write` span done programmatically or using config? (Need a reproducer - I am trying to construct one that mimics the user experience.)

In my quick experiment so far disabling tracing in config works for me to suppress the error message if Jaeger is not running.

**Comment by tjquinno** [comment]
Update:

Using this config
```yaml
tracing:
  service: helidon-tracing-service
  enabled: true
  components:
    web-server:
      spans:
        - name: "HTTP Request"
          new-name: "HTTP %1$s %2$s"
          logs:
            - name: "content-write"
              enabled: false
```
I find that:
1. There is no error message if I set `tracing.enabled` to `false`.
2. The `HTTP Request` span is correctly renamed to `HTTP <method> <path>`
3. Disabling `context-write` _does not_ seem to work.

Please provide a reproducer for the first two items. 

I will continue looking into the third.

**Comment by tjquinno** [comment]
![Tracing issue 8103 Jaeger screen capture](https://github.com/helidon-io/helidon/assets/24591185/693f95ce-2a99-4df6-9816-bbd05cc1686e)

**Comment by dalexandrov** [comment]
I can confirm point 1 and 2 are working ok with this config:

```
tracing:
  enabled: true
  service: helidon-se-1
  protocol: http
  port: 14250
  path: /api/traces
  tags:
    env: development
  sampler-type: "const"
  sampler-param: 1
  log-spans: true
  propagation: b3
  components:
    web-server:
      spans:
        - name: "HTTP Request"
          new-name: "HTTP %1$s %2$s %3$s"
          logs:
            - name: "content-write"
              enabled: false
```
