### ISSUE TITLE
Support Single Logout from Identity Provider (like IDCS) where token is passed as query parameter instead of cookie

### ISSUE THREAD

**Issue by tirunagaris** [helidon-io/helidon#8143]
## Environment Details
* Helidon Version: 3.2.3
* Helidon MP
* JDK version: JDK 17
* OS: Windows 10 Enterprise 22H2
* Docker version (if applicable): NA

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
We have two application based on Helidon MP (v 3.2.3) configured with OIDC security provider and registered with IDCS (Identity Provider) for achieving Single Sign On (SSO). Observed that logging out from one application is not logging out from other application; although SSO works. Expecting the logout from one helidon application would logout another helidon application via IDCS single logout.

This issue is easily reproducible with the OIDC configurations provide in below section.

In addition, found that the logout from application is invoking logout url of another application from IDCS, but its failing with 403 FORBIDDEN error.

Found below from the second application logs, (i.e., for the logout request from IDCS):

`Requested URI: GET /custom/logout?session_token=eyJ4NXQjUzI1NiI6IlZmcHZMeW9IclpPQUwzQXdYV3VHN2E5R0pBbXozaEtycXFzVlowV3kwTXMiLCJ4NXQiOiIwNE81dTRnQlMzMWlWQkkyZjk5eEtIb3E0R0kiLCJraWQiOiJTSUdOSU5HX0tFWSIsImFsZyI6IlJTMjU2In0.eyJzZXNzaW9uX2V4cCI6IjE3MDIzMDcwOTMiLCJzaWQiOiI4NTUxMWI3YTg3ZGI0ZWI2YjU2ZDFiMWM1YzU4NjRjZToxZGI0MzEifQ.JserxLzKDJviCVb9gKCNN1-YODr3UJDmfJYU50znBA3b-C0pX-rVtlhILehXp9efvZe-cPcXUXypymZYwieJMV_0HkZMStDBis7dBQWwHx5vM2ZlmR98zupD5-PkeZ54wlkQ2EWssH_UH9gLlP2ssTQ3ZUVzf9LjNUG6DEXnstkbk7ffBVIZM5ctYtu7WteaeElY_J_Fb37muyQ53LDD-8xEDj2SOhkSFmJiDvkjpJYYuVtb1s4raheCYrvYNbAax2XKKEnoqug5x3PBa-M0-xUixL03NgMAxWKilO6MoFJx9LYi_TAC6xciZmyW7iRoQ4G9z-XiXqXGEO3ErbxfPA`
seems like its missing ID Token cookie in the request:
```
2023.12.11 20:28:15 FINEST io.helidon.security.providers.oidc.OidcSupport Thread[#118,nioEventLoopGroup-3-2,10,main]: Missing tenant id, could not find in either of: [cookie]Falling back to the default tenant id: @default
2023.12.11 20:28:15 FINEST io.helidon.security.providers.oidc.OidcSupport Thread[#118,nioEventLoopGroup-3-2,10,main]: Logout request invoked without ID Token cookie
2023.12.11 20:28:15 FINE io.helidon.webserver.BareResponseImpl Thread[#118,nioEventLoopGroup-3-2,10,main]: [Response: 647250989, Channel: 0xa05a218c, StreamID: N/A] Response status is set to '403 Forbidden'
```

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"
Configure the security provider as below for both the Helidon MP applications. 
Run these applications and Register both the applications with identity provider (like IDCS).

Now invoke logout from one application and observed that the logout for second application is getting invoked from IDCS with session_token query parameter.

Used the below security configuration in both applications:
```
  providers:
    - abac:
      # Adds ABAC Provider - it does not require any configuration
    - oidc:
        header-use: true
        identity-uri: "${security.properties.idcs-uri}"
        client-id: "${security.properties.idcs-client-id}"
        client-secret: "${security.properties.idcs-client-secret}"
        audience: "${security.properties.idcs-uri}"
        scope-audience: "${security.properties.scope-audience}"
        redirect-uri: "/sr/test/topology"
        token-endpoint-auth: CLIENT_SECRET_POST
        cookie-name: "JSESSIONID"
        cookie-same-site: "LAX"
        logout-enabled: true
        logout-uri: "/custom/logout"
        post-logout-uri: "/greet/WelcomeUser"
        validate-jwt-with-jwk: false
        cookie-encryption-password: "lpmaster"   
        oidc-metadata:
          resource:
            uri: ${security.properties.idcs-uri}/.well-known/openid-configuration
    - idcs-role-mapper:
        multitenant: false
        oidc-config:
          # we must repeat IDCS configuration, as in this case
          # IDCS serves both as open ID connect authenticator and
          # as a role mapper. Using minimal configuration here
          client-id: "${security.properties.idcs-client-id}"
          client-secret: "${security.properties.idcs-client-secret}"
          identity-uri: "${security.properties.idcs-uri}"
```
