### ISSUE TITLE
4.x: io.helidon.dbclient.jdbc.spi.JdbcConnectionPoolProvider: module io.helidon.dbclient.jdbc does not declare `uses`

### ISSUE THREAD

**Issue by sdyura** [helidon-io/helidon#8237]
## Environment Details
* Helidon Version: **4.0.2**
* Helidon SE or Helidon MP: **SE**
* JDK version: **21**
* OS: **macOS**
* Docker version (if applicable):

----------

## Problem Description

I am trying to upgrade a Helidon 3 project to Helidon 4, but i am blocked by an error message when i try and config the DB

always happens, app it unable to launch

```
Exception in thread "main" java.util.ServiceConfigurationError: io.helidon.dbclient.jdbc.spi.JdbcConnectionPoolProvider: module io.helidon.dbclient.jdbc does not declare `uses`
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader.checkCaller(ServiceLoader.java:579)
	at java.base/java.util.ServiceLoader.<init>(ServiceLoader.java:507)
	at java.base/java.util.ServiceLoader.load(ServiceLoader.java:1698)
	at io.helidon.dbclient.jdbc@4.0.2/io.helidon.dbclient.jdbc.JdbcConnectionPool.create(JdbcConnectionPool.java:71)
	at io.helidon.config@4.0.2/io.helidon.config.ConfigValues.lambda$create$4(ConfigValues.java:168)
	at io.helidon.config@4.0.2/io.helidon.config.ConfigValues$GenericConfigValueImpl.asOptional(ConfigValues.java:255)
	at io.helidon.common.mapper@4.0.2/io.helidon.common.mapper.OptionalValue.ifPresent(OptionalValue.java:188)
	at io.helidon.dbclient.jdbc@4.0.2/io.helidon.dbclient.jdbc.JdbcClientBuilder.config(JdbcClientBuilder.java:56)
	at io.helidon.dbclient.jdbc@4.0.2/io.helidon.dbclient.jdbc.JdbcClientBuilder.config(JdbcClientBuilder.java:27)
	at io.helidon.dbclient@4.0.2/io.helidon.dbclient.DbClient$Builder.config(DbClient.java:206)
	at io.helidon.dbclient@4.0.2/io.helidon.dbclient.DbClient.builder(DbClient.java:151)
```

what the error says seems to be true, the file https://github.com/helidon-io/helidon/blob/main/dbclient/jdbc/src/main/java/module-info.java does NOT have a uses for 'io.helidon.dbclient.jdbc.spi.JdbcConnectionPoolProvider' and yet is trying to load it.

## Steps to reproduce

trying to setup a connectionPool

```
db:
  source: jdbc
  connection:
    url: jdbc:postgresql://XXX:5432/postgres
    username: XXX
    password: XXX
    poolName: hikariPool
    initializationFailTimeout: -1
    connectionTimeout: 2000
    maximumPoolSize: 1
    minimumIdle: 0
```
