### ISSUE TITLE
[4.x] Feature weight is not honored in server routing

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#8550]
When features are discovered automatically, and a weight is customized, it is ignored by routing in webserver.

To reproduce:
Quickstart SE
Update applicaiton.yaml with this:
```yaml
server:
  port: 8080
  host: 0.0.0.0
  # default behavior to discover Server features (observability, openapi, metrics)
  # features-discovers-services: true
  # all of the below is discovered automatically
  features:
    observe:
      weight: 120
```

In Main.java:
```java
routing.register("/greet", new GreetService())
                .get("/observe/health", (req, res) -> res.send("From routing"));
```

We expect that the endpoint `http://localhost:8080/observe/health` should return appropriate response from Health observer, and not the "From routing" response.

Right now it returns "From routing", so the change in configuration was not honored.
