### ISSUE TITLE
[4.x] Support for multiple sockets with Security feature through configuration

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#8557]
Currently we cannot have a security configuration different for different sockets. As a result, we need to work around it by updating the routing directly with security setup.
This requires us to disable server feature discovery, as otherwise the features get registered twice.

as seen in:
examples/security/outbound-override/src/main/java/io/helidon/security/examples/outbound/OutboundOverrideJwtExample.java
examples/security/outbound-override/src/main/java/io/helidon/security/examples/outbound/OutboundOverrideExample.java
examples/security/webserver-signatures/src/main/java/io/helidon/examples/security/signatures/SignatureExampleBuilderMain.java

We should design a better way of handling such scenarios, ideally directly in configuration.
Example of an option:
```yaml
server:
  features:
    security:
      sockets:
        - name: "admin"
          paths:
        - name: "@default"
          paths: 
```
