### ISSUE TITLE
OpenAPI generator operations grouping

### ISSUE THREAD

**Issue by m0mus** [helidon-io/helidon#8635]
## Environment Details
* Helidon Version: 4.0.7
* OpenAPI generator version: 6.2.1
* Helidon MP
* JDK version: 21
* OS: Windows

I faced this issue when I was working on migrating Spring Petclinic Rest project to Helidon. Services generated by Helidon differ from services generated by Spring OponAPI generator in a way that some methods are placed in different services. It looks like Spring is grouping operations by URL and Helidon by tag.

Example:

`addPetToOwner` operation is declared like this:

```
  /owners/{ownerId}/pets:
    post:
      tags:
        - pet
      operationId: addPetToOwner
      summary: Adds a pet to an owner
      description: Records the details of a new pet.
```  

Spring genertor places it into `OwnersApi`:

```
@Validated
@Tag(name = "owners", description = "Endpoints related to pet owners.")
public interface OwnersApi {
	...
    default ResponseEntity<PetDto> addPetToOwner(
        @Min(0) @Parameter(name = "ownerId", description = "The ID of the pet owner.", required = true, in = ParameterIn.PATH) @PathVariable("ownerId") Integer ownerId,
        @Parameter(name = "PetFieldsDto", description = "The details of the new pet.", required = true) @Valid @RequestBody PetFieldsDto petFieldsDto
    ) {
    	...
    }
    ...
}
```

Helidon places it into `Pet`:

```
@Path("")
public interface PetService {
    ...
    @POST
    @Path("/owners/{ownerId}/pets")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Response addPetToOwner(@PathParam("ownerId") @Min(0) Integer ownerId, @Valid @NotNull PetFieldsDto petFieldsDto);
    ...
}
```

Helidon generated code introduced paths collision because `OwnerService` base path is `\owners`.

```
@Path("/owners")
public interface OwnerService {
}
```
