### ISSUE TITLE
[4.x] Server TLS Documentation

### ISSUE THREAD

**Issue by hrstoyanov** [helidon-io/helidon#8926]
The TLS server configuration documentation [here](https://helidon.io/docs/v4/se/webserver#_configuring_tls) only shows how to access the p12/p8 files as resources on the class path (e.g. using **resource-path** property). Please document that store files can also reside anywhere, with the **path** property. Otherwise the developers will waste time trying to figure out why they are getting "file not found" exception, without realizing  that only the class path is searched when using  **resource-path** .

```
server:
  tls:
    #Truststore setup
    trust:
      keystore:
        passphrase: "password"
        trust-store: true
        resource:
          path: "keystore.p12"
    # Keystore with private key and server certificate
    private-key:
      keystore:
        passphrase: "password"
        resource:
          path: "keystore.p12"
```
