### ISSUE TITLE
Support to add ABAC policy in configuration for explicit authorization

### ISSUE THREAD

**Issue by karancsn** [helidon-io/helidon#8948]
## Environment Details
* Helidon Version: 4.0.10
* Helidon SE or Helidon MP: Helidon MP
* JDK version: Oracle JDK 21.0.1
* OS: Windows (applicable on all platforms)
* Docker version (if applicable): N/A

----------

## Problem Description
We need a support to define Authorization (AuthZ) rules at deployment time to protect a Jersey Resource.
For instance, 
* Deployment A will allow users with role/group "admin-users" access a resource while in deployment B, same resource will be allowed to users with role/group "super-users".
* The rules will not be limited to roles alone but will also consider data; for instance, a user with the role "regular-csr" may POST a refund up to a maximum of $1000.00.  

ABAC support currently available seems like a good fit; an expression like `inRole('admin-users") && object.amount <= 1000` would enforce the required restriction on resource.

But, at the moment, `object` requires the AuthZ as **explicit = true**.
If _application.yaml_ contains a rule specified in `security.web-server.paths[].abac`, then evaluation is done before the Resource code gets the control to check for authorization. Here, `object = null` and check fails.

At the same time, we can't fix the configuration in code as the rules can vary in different deployments.

## Expectation
Allow defining the rules in configuration file, (application.yaml), so it can be customized per deployment environment without changing the code.
Possibly, `security.web-server.paths[].abac` or `security.web-server.paths[].abac.policy-validator` can support a new key as **explicit** to decide if its evaluation should be deferred, so there is no impact to existing consumers.

**Comment by karancsn** [comment]
@Verdent 
Could you please update me on the status of this issue? Has it been accepted as an enhancement, or is it still under evaluation?

Thank you for your assistance.
Should you require any further details to expedite the process, do let me know.

**Comment by karancsn** [comment]
**Update**
For your information, we will be defining a new ABAC validator as follows:
```yaml
server:
    features:
        security:
            paths:
            -   path: "/xyz"
                methods:
                authenticate: true
                abac:
                    rule-validator:
                    -   name: ""
                        roles-allowed: []
                        scopes-allowed: []
                        chained-validators: # Supports all default ABAC validators, except Role/Scope
                          policy-validator:
                              statement: ""

```
This enhancement will allow us to defer the evaluation of ABAC until the `object` becomes available.

I hope this will be helpful as you work on this issue. Please let us know if you would like us to review and consider early modifications to our validator according to your design plan.
