### ISSUE TITLE
4.x: Throughput limit ("requests per second")

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#9381]
Add a concurrency limit that handles number of operations per time unit, such as "max 10 requests/second"

- add to concurrency limits
- maybe introduce a fault tolerance feature as well (can be follow up issue)
- maybe introduce a web client feature as well (can be follow up issue)

Configuration example:
```yaml
limit:
  throughput:
    amount: 10
    duration: PT1S # 10 per second
```
