### ISSUE TITLE
4.x: Static content from classpath improvements

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#9471]
Currently we generate temporary files for extracted jar entries as `ws-****.je`

A few improvements could be done:
- use `helidon-` (or `helidon-ws`) prefix to clearly bind them to Helidon
- add configuration option to cache in-memory only (probably to a certain size), to avoid creating the files altogether

**Comment by tomas-langer** [comment]
> Is it possible to process the files as they are extracted from the class path? For example, CSS files may have comments, that I might not want to serve to the client , and would like to strip off.

I think this should be done at build time and your deployment should contain the files you want to serve (minified css, javascript etc.).

Also Helidon does not have such a feature, as we need to work with the content length of the file (i.e. when a range is requested, to correctly provide `Content-Length` header etc.). Such operations would introduce quite an overhead (I can imagine this being implemented, but I would rather not)

**Comment by tomas-langer** [comment]
The PR will have the following updates:
- support for configuration based setup of static content (currently only possible through API)
- introduces static content server feature to do so (can be used programmaticaly and through config)
- introduces more configurable temporary storage (enabled, location, prefix, suffix), shared by all handlers, with possibility to customize per handler
- introduces more configurable memory storage (enabled, maximal size in bytes), shared by all handlers, with possibility to customize per handler
- when using classpath, if cached in memory, no temporary file gets created
- when using classpath, when using temporary files, we have a shutdown hook to delete them
- when using classpath, when temporary storage is disabled, files are served directly from jar input stream

Example of a configuration:
```yaml
server:
  features:
    # the new static content feature, automatically discovered
    static-content:
      # (optional) configuration of temporary storage
      temporary-storage:
        directory: "./target/helidon/tmp"
        file-prefix: "helidon-custom"
        file-suffix: ".cache"
        # delete-on-exit: false
      # classpath handlers (context to serve on webserver and location on classpath)
      classpath:
        - context: "/classpath"
          location: "web"
        - context: "/singleclasspath"
          location: "web/resource.txt"
      # file system handlers (context to serve on webserver and location on file system)
      path:
        - context: "/path"
          location: "./src/test/resources/web"
        - context: "/singlepath"
          location: "./src/test/resources/web/resource.txt"
```
