### ISSUE TITLE
Update gRPC client docs for 4.1 to include an example of a channel configuration without TLS

### ISSUE THREAD

**Issue by rlubke** [helidon-io/helidon#9491]
The configuration section for the gRPC client in 4.1 doesn't state that if you're not using TLS, you still need to define TLS configuration in order to produce a plaintext gRPC channel.

For example, in order to avoid an exception attempting to use the default channel in plaintext mode:

```yaml
grpc:
  client:
    channels:
      - name: "default"
        tls:
          enabled: "false"
```

## Environment Details
* Helidon Version: 4.1.3
* Helidon MP
* JDK version: java version "21.0.5" 2024-10-15 LTS
* OS: MacOS 14.7.1 (apple silicon)

----------

## Problem Description
An exception will be raised if trying to use a channel without TLS per the documentation:

```yaml
grpc:
  client:
    channels:
      - name: "default"
```

## Steps to reproduce
Try to inject a client proxy using the default channel with no yaml configuration or configuration as described in the Problem Description section.  An exception will be thrown stating the requirement of a TLS  configuration.
