### ISSUE TITLE
4.x: MP OIDC guide uses cookie-use=false

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#9518]
## Environment Details
* Helidon Version: 4.1.4
* Helidon MP

----------

## Problem Description

The Helidon MP OIDC Security Provider guide does not work, authentication does not work.

Unlike the SE guide, the MP guide uses `cookie-use=false`, see the [docs](https://github.com/helidon-io/helidon/blob/4.1.4/docs/src/main/asciidoc/mp/guides/security-oidc.adoc#add-oidc-security-properties).

The change was introduced in https://github.com/helidon-io/helidon/pull/8868

I.e.

```yaml
security:
  providers:
    - oidc:
        # ...
        cookie-use: "false"
```

AFAIK the redirect endpoint uses either cookie or query param to pass the tokens to the original URI.
