### ISSUE TITLE
Extended metrics do not change to snake case

### ISSUE THREAD

**Issue by hyder** [helidon-io/helidon#9791]
## Environment Details
* Helidon Version: 4.1.6
* Helidon SE
* JDK version: 21
* OS:

----------

## Problem Description
Metrics settings:

```yaml
metrics:
  built-in-meter-name-format: SNAKE
  gc-time-type: gauge
  key-performance-indicators:
    extended: true
```

When setting the meter format to `SNAKE`, most settings take snake format except for the KPI metrics:

```
# HELP requests_inFlight  
# TYPE requests_inFlight gauge
```

Additionally, also note that there is no description as to what it captures. Steps to reproduce: https://helidon.io/docs/latest/se/guides/metrics#basic-and-extended-kpi
