### ISSUE TITLE
Inner Config node is not visible when returned as Map<String, String>

### ISSUE THREAD

**Issue by Tomas-Kraus** [helidon-io/helidon#9834]
Have following method in Config blueprint:
```Java
    @Option.Configured
    @Option.Singular("property")
    Map<String, String> properties();
```

and related config yaml:
```yaml
data:
  provider.jakarta:
    ...
    properties:
      eclipselink.target-database: "MySQL"
      eclipselink.target-server: "None"
      eclipselink.weaving: false
      # Broken, this property is missing in PU properties
      eclipselink.logging.level: "FINEST"
      eclipselink.logging.level.weaver: "OFF"
      eclipselink.logging.parameters: true
      jakarta.persistence.schema-generation.database.action: drop-and-create
```

Node `eclipselink.logging.level` is not returned in properties `Map`.
