### ISSUE TITLE
Helidon Config Profile fails to return the name of active profile

### ISSUE THREAD

**Issue by java-tejaswini** [helidon-io/helidon#9920]
## Environment Details
* Helidon Version: 4.1.6
*  Helidon MP
* JDK version: 21
* OS: Windows

----------

## Problem Description

I have set profile using `helidon.config.profile=test` in properties file. The **test** profiles values are getting picked up as well. However when i try to hit /observe/config/profile, i am receiving the response but it is giving **{"name":""}** .
**The expected response is {"name" : "test"}.** 
## Steps to reproduce

The configuration which i am using is,
```yaml
server:
  features:
    observe:
      sockets: "observe"
      observers:
        config:
          permit-all: true
mp:
  config:
    profile : test
```

Also i am having microprofile-config-test.properties file in META-INF
